# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"

  # Jakir node
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.56.11"
    

    ubuntu.vm.provider "libvirt" do |lv|
      lv.memory = 2048
      lv.cpus   = 2
    end
  end
end

